/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import libs.Util;
import model.Atividade;
import model.AtividadeDAO;
import model.JdbcAtividadeDao;

/**
 *
 * @author Augusto-PC
 */
public class CriarAtividade extends javax.swing.JInternalFrame {
    AtividadeDAO at = new JdbcAtividadeDao() {};
    DefaultTableModel tableModel = new DefaultTableModel();
    Util util = new Util();
    ArrayList<JTextField> listCampos = new ArrayList<JTextField>();
        
    /**
     * Creates new form CriarAtividade
     */
    public CriarAtividade() {
        initComponents();
        
        String[] colunas = new String[4];
        
        colunas[0] = "Id";
        colunas[1] = "Número de Cursos";
        colunas[2] = "Número de Participantes";
        colunas[3] = "Localização";
        
        tableModel.setColumnIdentifiers(colunas);
        tblLista.setModel(tableModel);
        
        listCampos.add(txtLocal);
        listCampos.add(txtNumCursos);
        listCampos.add(txtNumPart);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumCursos = new javax.swing.JTextField();
        txtNumPart = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Criar Atividade");

        jLabel2.setText("Número de Cursos");

        jLabel3.setText("Número de Participantes");

        jLabel4.setText("Localização");

        btnCriar.setText("Salvar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLista);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel5.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCursos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumPart, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocal))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCriar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnListar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        util.LimpaTabela(tableModel);
        ArrayList<Atividade> list = at.listar();
        for (Atividade atividade : list) {
            String[] valores = new String [4];
            
            valores[0] = atividade.getId()+"";
            valores[1] = atividade.getMaxCurso()+"";
            valores[2] = atividade.getMaxParticipante()+"";
            valores[3] = atividade.getLocalizacao();
            
            tableModel.addRow(valores);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        if(util.Valida(listCampos)){
            Atividade atividade = new Atividade();

            atividade.setMaxCurso(Integer.parseInt(txtNumCursos.getText()));
            atividade.setMaxParticipante(Integer.parseInt(txtNumPart.getText()));
            atividade.setLocalizacao(txtLocal.getText());
        
            if(at.gravar(atividade)){
                JOptionPane.showMessageDialog(null, "Inserido com sucesso");
                util.LimpaCampos(listCampos);
            }else{
                JOptionPane.showMessageDialog(null, "Falha na inserção");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Preencha todos os campos.");
        }
        
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        listCampos.add(txtId);
        
        Atividade atividade = new Atividade();
        atividade.setId(Integer.parseInt(txtId.getText()));
        
        if(at.excluir(atividade)){
            JOptionPane.showMessageDialog(null, "Excluido com sucesso");
            util.LimpaCampos(listCampos);
        }else{
            JOptionPane.showMessageDialog(null, "Falha na exclusão");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        listCampos.add(txtId);
        
        if(util.Valida(listCampos)){
            Atividade atividade = new Atividade();
            
            atividade.setId(Integer.parseInt(txtId.getText()));
            atividade.setMaxCurso(Integer.parseInt(txtNumCursos.getText()));
            atividade.setMaxParticipante(Integer.parseInt(txtNumPart.getText()));
            atividade.setLocalizacao(txtLocal.getText());
            
            if(at.alterar(atividade)){
                JOptionPane.showMessageDialog(null, "Alterado com sucesso");
                util.LimpaCampos(listCampos);
                btnListarActionPerformed(evt);                                          
            }else{
                JOptionPane.showMessageDialog(null, "Falha na Alteração");
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseClicked
         int linha = tblLista.getSelectedRow();
         System.out.println(linha);
         
         txtId.setText(tblLista.getValueAt(linha,0)+"");
         txtNumCursos.setText(tblLista.getValueAt(linha,1)+"");
         txtNumPart.setText(tblLista.getValueAt(linha,2)+"");
         txtLocal.setText(tblLista.getValueAt(linha,3)+"");

    }//GEN-LAST:event_tblListaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNumCursos;
    private javax.swing.JTextField txtNumPart;
    // End of variables declaration//GEN-END:variables
}
